# Generated by Django 6.0.5 on 2026-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
