# Generated by Django 6.0.5 on 2026-05-25 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBook', '0002_employee_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Почта')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('category', models.CharField(choices=[('client', 'Клиент'), ('partner', 'Партнёр'), ('supplier', 'Поставщик'), ('other', 'Другое')], default='client', max_length=20, verbose_name='Категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Внешний контакт',
                'verbose_name_plural': 'Внешние контакты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
